name: Tests

on:
  push:
    branches: [ master, main, develop ]
  pull_request:
    branches: [ master, main ]
  workflow_dispatch:

jobs:
  test:
    name: Test Python ${{ matrix.python-version }} on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: ['3.10', '3.11', '3.12', '3.13']

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install build dependencies
        run: |
          python -m pip install --upgrade pip
          pip install "numpy>=1.21.0,<2.0.0"  # Install NumPy first for proper detection
          pip install "meson-python>=0.15.0" "Cython>=3.0.0" meson ninja build

      - name: Build and install package
        run: |
          # Ensure NumPy is available for build
          python -c "import numpy; print(f'NumPy {numpy.__version__} found at {numpy.get_include()}')"
          python -m build --wheel
          pip install dist/*.whl

      - name: Install test dependencies
        run: |
          pip install pytest pytest-cov
          pip install pandas biopython "pysam>=0.23.3" scipy matplotlib logomaker patchworklib

      - name: Run tests with coverage
        run: |
          pytest tests/ -v --cov=seqpandas --cov-report=term-missing --cov-report=xml

      - name: Upload coverage to Codecov
        if: matrix.os == 'ubuntu-latest' && matrix.python-version == '3.11'
        uses: codecov/codecov-action@v3
        with:
          file: ./coverage.xml
          flags: unittests
          name: codecov-umbrella
          fail_ci_if_error: false

  lint:
    name: Pre-commit Checks
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Run pre-commit
        uses: pre-commit/action@v3.0.0
